const $=s=>document.querySelector(s),socket=io();let mode="login",user=null,timer=null,sec=60;
const screens=["auth","home","lobby","game","result"];function show(x){screens.forEach(s=>$("#"+s).classList.toggle("hidden",s!==x));scrollTo(0,0)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("#at").textContent=mode==="login"?"Bem-vindo de volta":"Crie sua conta";$("#as").textContent=mode==="login"?"Entre para continuar sua jornada.":"Só precisa de um nickname e uma senha.";$("form .primary")?.remove?.();$("#form button").textContent=mode==="login"?"Entrar":"Criar conta";$("#err").textContent=""});
$("#form").onsubmit=async e=>{e.preventDefault();$("#err").textContent="";try{let r=await fetch(mode==="login"?"/api/login":"/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nickname:$("#nick").value.trim(),password:$("#pass").value})}),d=await r.json();if(!r.ok)throw Error(d.error);user=d.user;$("#hello").textContent="Olá, "+user.nickname;show("home")}catch(x){$("#err").textContent=x.message}};
$("#logout").onclick=()=>{user=null;show("auth")};$("#football").onclick=()=>{show("lobby");$("#panel").classList.add("hidden");$("#rerr").textContent=""};$("#back").onclick=()=>show("home");
$("#create").onclick=()=>socket.emit("room:create",{nickname:user.nickname});$("#join").onclick=()=>socket.emit("room:join",{nickname:user.nickname,code:$("#code").value});
$("#ready").onclick=()=>socket.emit("room:ready");$("#surrender").onclick=()=>{if(confirm("Desistir desta sala?"))socket.emit("room:surrender")};
$("#copy").onclick=async()=>{await navigator.clipboard?.writeText($("#roomcode").textContent);$("#copy").textContent="Copiado!";setTimeout(()=>$("#copy").textContent="Copiar",1200)};
socket.on("room:error",m=>$("#rerr").textContent=m);
socket.on("room:update",r=>{show("lobby");$("#panel").classList.remove("hidden");$("#roomcode").textContent=r.code;$("#players").innerHTML=r.players.map(p=>`<div class="player"><span>${esc(p.nickname)}</span><span class="badge ${p.ready?"ready":""}">${p.surrendered?"Desistiu":p.ready?"Pronto":"Aguardando"}</span></div>`).join("");$("#rstatus").textContent=`${r.players.filter(p=>p.ready||p.surrendered).length}/${r.players.length} concluíram`});
socket.on("game:start",()=>show("game"));socket.on("game:question",q=>{clearInterval(timer);$("#rn").textContent=q.number;$("#cat").textContent=q.category;$("#q").textContent=q.question;$("#prog").style.width=q.number/200*100+"%";$("#opts").innerHTML=q.options.map((o,i)=>`<button class="opt" data-i="${i}">${esc(o)}</button>`).join("");document.querySelectorAll(".opt").forEach(b=>b.onclick=()=>{document.querySelectorAll(".opt").forEach(x=>x.disabled=true);socket.emit("game:answer",{index:+b.dataset.i})});sec=60;$("#tm").textContent=sec;timer=setInterval(()=>{sec--;$("#tm").textContent=sec;if(sec<=0){clearInterval(timer);socket.emit("game:timeout")}},1000)});
socket.on("game:finished",r=>{clearInterval(timer);let w=r.result==="win";$("#ricon").textContent=w?"🏆":"💀";$("#reye").textContent=w?"200 RODADAS CONCLUÍDAS":"PARTIDA ENCERRADA";$("#rt").textContent=w?"Você venceu!":"Derrota";$("#rx").textContent=w?"Vocês acertaram as 200 rodadas sem repetir perguntas.":"Uma resposta errada, tempo esgotado ou desistência encerrou a partida.";show("result")});
$("#again").onclick=()=>show("lobby");$("#home").onclick=()=>show("home");function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}